defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: asc_development

test:
  <<: *defaults
  database: asc_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['mongodb://heroku:ym28h6ww0gxz5dq92o7v5e@flame.mongohq.com:27069/app446485'] %>
