require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CalculatorsController do

  def mock_calculator(stubs={})
    @mock_calculator ||= mock_model(Calculator, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all calculators as @calculators" do
      Calculator.stub(:all) { [mock_calculator] }
      get :index
      assigns(:calculators).should eq([mock_calculator])
    end
  end

  describe "GET show" do
    it "assigns the requested calculator as @calculator" do
      Calculator.stub(:find).with("37") { mock_calculator }
      get :show, :id => "37"
      assigns(:calculator).should be(mock_calculator)
    end
  end

  describe "GET new" do
    it "assigns a new calculator as @calculator" do
      Calculator.stub(:new) { mock_calculator }
      get :new
      assigns(:calculator).should be(mock_calculator)
    end
  end

  describe "GET edit" do
    it "assigns the requested calculator as @calculator" do
      Calculator.stub(:find).with("37") { mock_calculator }
      get :edit, :id => "37"
      assigns(:calculator).should be(mock_calculator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created calculator as @calculator" do
        Calculator.stub(:new).with({'these' => 'params'}) { mock_calculator(:save => true) }
        post :create, :calculator => {'these' => 'params'}
        assigns(:calculator).should be(mock_calculator)
      end

      it "redirects to the created calculator" do
        Calculator.stub(:new) { mock_calculator(:save => true) }
        post :create, :calculator => {}
        response.should redirect_to(calculator_url(mock_calculator))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calculator as @calculator" do
        Calculator.stub(:new).with({'these' => 'params'}) { mock_calculator(:save => false) }
        post :create, :calculator => {'these' => 'params'}
        assigns(:calculator).should be(mock_calculator)
      end

      it "re-renders the 'new' template" do
        Calculator.stub(:new) { mock_calculator(:save => false) }
        post :create, :calculator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calculator" do
        Calculator.stub(:find).with("37") { mock_calculator }
        mock_calculator.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :calculator => {'these' => 'params'}
      end

      it "assigns the requested calculator as @calculator" do
        Calculator.stub(:find) { mock_calculator(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:calculator).should be(mock_calculator)
      end

      it "redirects to the calculator" do
        Calculator.stub(:find) { mock_calculator(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(calculator_url(mock_calculator))
      end
    end

    describe "with invalid params" do
      it "assigns the calculator as @calculator" do
        Calculator.stub(:find) { mock_calculator(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:calculator).should be(mock_calculator)
      end

      it "re-renders the 'edit' template" do
        Calculator.stub(:find) { mock_calculator(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calculator" do
      Calculator.stub(:find).with("37") { mock_calculator }
      mock_calculator.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the calculators list" do
      Calculator.stub(:find) { mock_calculator }
      delete :destroy, :id => "1"
      response.should redirect_to(calculators_url)
    end
  end

end
